name: Counter App
description: a flutter stepper widget with nice aniamtion
version: 0.0.1
author: Raj Chowdhury
homepage: https://github.com/Rajchowdhury420
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

// add your own requirement if u want
